### ISSUE TITLE
Duplicated atom names

### ISSUE THREAD

**Issue by gandrianov** [matteoferla/rdkit_to_params#1]
Hello @matteoferla,

Thank you for this tool, it saved me a lot of time. But I noticed some problem with atom names. If you look on the attached params file, then you can almost identical atom names on lines #24 and #28. I guess for the first line template for atom name was generated by template <Element><Greek Letter><Number> and for second <ElementNumber>. Do you know fast way how to solve this problem?

[1.mol2.txt](https://github.com/matteoferla/rdkit_to_params/files/7248066/1.mol2.txt)
[1.params.txt](https://github.com/matteoferla/rdkit_to_params/files/7248067/1.params.txt)

**Comment by gandrianov** [comment]
Solved by `Params.greekification = False` 

Thank you

**Comment by matteoferla** [comment]
Sorry, I always miss GitHub notifications (Gmail puts them in the spammy Forum tab... hopefully the GitHub mobile app will fix this for me!).

I have corrected the really embarrassing bug in `greekify` that was resulting in only the first atom at a given distance from the reference atom to become Greek lettered.

Thank you for pointing out the bug!
