### ISSUE TITLE
Inquiry about the Connection of Ligand to Residue via Double Bond

### ISSUE THREAD

**Issue by ZhaoKe-BIT** [matteoferla/rdkit_to_params#2]
Hello, @matteoferla！
Rdkit_to_params is a fantastic tool that has greatly helped me solve numerous issues, and I want to express my gratitude! 
However, I've encountered a problem. My ligand is the ZFJ, derived from the protein with pdbid=7mfx, which is connected to the LYS on the protein through a C=N double bond formed by a Schiff base reaction. Is there a way to take this into consideration when generating the constraint file? 
Your assistance on this matter would be greatly appreciated!

**Comment by matteoferla** [comment]
>that has greatly helped me solve numerous issue

I am happy to hear that

> when generating the constraint file
I should say that the [Constraint class](https://github.com/matteoferla/rdkit_to_params/blob/eebfc042975cf2c925148e36acd893d3b62f3e5e/rdkit_to_params/constraint.py#L24) is odd as it spits out constraint files to be useful for Rosetta users, whereas in PyRosetta I'd not bother and add constraints directly to the pose ([example](https://github.com/matteoferla/pyrosetta-help/blob/4d384a2c246b2e6679f6a7e9bc762e7d82042fbd/pyrosetta_help/alphafold/constraints.py#L116)).
So I actually never use it as I operate solely with PyRosetta space.
Plus, on a quick gander I don't think passing a double bond would work.

There is an extra level of detail that may or may not cause problem: the atom types as C23 (the connection on the ligand side) has a sp2 not sp3 hybridisation state —which would slightly affect bond lengths etc. So I would probably generate the topology for `CCN(CC)c1ccc-2c(c1)C(c3c2ccc(c3)/C=C/C=N)(C)C`:
![image](https://github.com/matteoferla/rdkit_to_params/assets/11302983/098ea167-73c9-44d9-ba4c-25f18944909d)
with names from the PDB (so with Lys NZ via PyMOL surgery).

But that is a minor detail.


So definiting the names based on https://www.ebi.ac.uk/pdbe/static/files/pdbechem_v2/ZFJ_ideal.pdb
and getting the angles:
```python
from rdkit import Chem
from rdkit.Chem import AllChem

imine: Chem.Mol = Chem.MolFromSmiles('C/C=NC')
imine
```
![image](https://github.com/matteoferla/rdkit_to_params/assets/11302983/32326245-d688-44e0-ad88-68d3645cf5d7)
```python
AllChem.EmbedMolecule(imine)
antecedent_idx = 0
antecedent_name = 'C22'
connecting_idx = 1
connecting_name = 'C23'
nitrogen_idx = 2
nitrogen_name = 'NZ'
descendant_idx = 3
descendant_name = 'CE'
conf: Chem.Conformer = imine.GetConformer()

antecedent_angle: float = Chem.rdMolTransforms.GetAngleRad(conf, antecedent_idx, connecting_idx,nitrogen_idx)
descendant_angle: float = Chem.rdMolTransforms.GetAngleRad(conf, connecting_idx,nitrogen_idx, descendant_idx)
dihedral_angle: float = Chem.rdMolTransforms.GetDihedralRad(conf, antecedent_idx, connecting_idx,nitrogen_idx, descendant_idx)

print(f'Angle {antecedent_name} \U0001F47EB {connecting_name} \U0001F47EB {nitrogen_name} \U0001F47EA HARMONIC {antecedent_angle:.2f} \U0001F47E')
print(f'Angle {connecting_name} \U0001F47EB {nitrogen_name} \U0001F47EA {descendant_name} \U0001F47EA HARMONIC {descendant_angle:.2f} \U0001F47E')
print(f'Dihedral {antecedent_name} \U0001F47EB {connecting_name} \U0001F47EB {nitrogen_name} {nitrogen_name} \U0001F47EA {descendant_name} \U0001F47EA CIRCULARHARMONIC {dihedral_angle:.2f} \U0001F47E')
```
Gives

    Angle C22 👾B C23 👾B NZ 👾A HARMONIC 2.15 👾
    Angle C23 👾B NZ 👾A CE 👾A HARMONIC 2.12 👾
    Dihedral C22 👾B C23 👾B NZ NZ 👾A CE 👾A CIRCULARHARMONIC 3.14 👾

3.14 is pi. so can be zero radians.
The last placeholder is the sigma. 5° is like short of 0.1, so something like that —an arbitrary number on the 0.1–0.5 range.

**Comment by ZhaoKe-BIT** [comment]
Thank you for your prompt response! My code is mainly built using RosettaScripts, so I do plan to utilize a constraint file. 
I understand that constraint files can only be constructed with single bonds. To align with my subsequent work, I intend to build the entire LYS with ZFJ as a non-standard residue. I've used this approach before, just adjusting the 'connect' in params to the corresponding lower or upper connect. Thanks again; your response and work have been immensely beneficial! 
Additionally, I have a question: when using the from_smiles_w_pdbfile function, is there a way to directly obtain the corresponding constraints from the pdb file?

**Comment by matteoferla** [comment]
> I understand that constraint files can only be constructed with single bonds

Bond order is not really a thing in MM: atoms are described by atom types which include element, hybridisation state and other properties. They are in the topology definition solely for output purposes.
But yes, the bond order is not definable in the connections. However, the important thing is that it is planar (sp2) as you can append the CONECT to the file to fix the

> build the entire LYS with ZFJ as a non-standard residue

The number of rotatable bonds will be rather high. Having it as a patch on norleucine (`NLE`) may be better if the double bond is essential in the output w/o re-adding it

**Comment by ZhaoKe-BIT** [comment]
Thank you very much for your advice and guidance. I will implement these methods in the hope of achieving a correct system. However, due to time constraints, this is likely to be completed by next week. 

Once again, I sincerely appreciate your assistance and wish you all the best!

**Comment by ZhaoKe-BIT** [comment]
Thanks a lot for your valuable advice. I have successfully completed this simulation! I will now close this issue. Have a pleasant weekend!
